### PR TITLE
Add distributional models

### LINKED ISSUE #606: Figure in Sleepstudy example not being reproducible
Seems the code used to generate the scatterplot is not working anymore 

image

I'm trying this but I don't like the end result 

```python
idata.posterior.plot.scatter(
    x="1|Subject", y="Days|Subject",
    hue="Subject__factor_dim",
    hue_style="discrete",
    add_colorbar=False,
    add_legend=False,
    ax=ax
)
```

image

I have ArviZ 0.14.0 and xarray 2022.11.0

### PR DESCRIPTION
**Pull request by tomicapretto**
Exciting changes are coming... TBD

Also closes #606, #449

### CODE REVIEW

**Comment by tomicapretto** [comment]
To be done:

* [ ] Rewrite existing tests / Make sure they pass
  * [ ] `test_alias.py`
  * [ ] `test_built_models.py`
  * [ ] `test_data.py`
  * [ ] `test_formula.py`
  * [ ] `test_model.construction.py`
  * [ ] `test_predict.py`
  * [ ] `test_prior.py`
  * [ ] `test_utils.py`
* [ ] Add tests for distributional models
* [ ] Rewrite `plot_cap()` and friends
  * I'm thinking we could use `seaborn` for this function in the future because its nice new API following the grammar of graphics.

**Comment by tomicapretto** [comment]
I don't expect to add any changes now. The example I wrote is not listed in the documentation because it's not polished. At this point, it's been **so many** many changes in this massive PR that I just want to merge and move on :smile:

**Comment by aloctavodia** [comment]
There are so many changes here! I suggest trusting the tests and merging so you can enjoy a well-deserved weekend!

**Comment by zwelitunyiswa** [comment]
Argentina wins the World Cup and my man @tomicapretto goes full code beast mode. I would have thought you still would be recovering from partying on the Avenida 9 de Julio!

**Comment by tomicapretto** [comment]
> Argentina wins the World Cup and my man @tomicapretto goes full code beast mode. I would have thought you still would be recovering from partying on the Avenida 9 de Julio!

Haha, thanks! I don't live in Buenos Aires but celebrations here (Rosario) were incredible as well!

**Pull request merged**
