### PR TITLE
Change one reference link and the names to PyMC.

### PR DESCRIPTION
**Pull request by apachaves**
Change one reference link and the names to PyMC to comply to the project's new name.

### CODE REVIEW

**Comment by aloctavodia** [comment]
Hi @apachaves thanks for your contribution. We have  a branch v4, where we are adding changes related to PyMC 4.x.

**Comment by apachaves** [comment]
Hi @aloctavodia, no problem. PyMC4 (based on Tensorflow) was discontinued, no? Not sure now... But I believe that PyMC3 (based on Theano) was rebranded to PyMC during the time Theano was discontinued and later adopted and rebranded as Aesara.

**Comment by aloctavodia** [comment]
You are right. PyMC4 has been abandoned. And PyMC 4.0 is comming soon, which is based on aesara (a rewrite of theano). 

All changes related to PyMC 4.0 are going into the v4 branch. We will merge that branch into main once PyMC 4.0 is released.

**Comment by apachaves** [comment]
All these C4s and C 4.0s confused me. haha Got it! It is clear now. Thank you!

**Comment by canyon289** [comment]
> All these C4s and C 4.0s confused me. haha Got it! It is clear now. Thank you!

Trust me, its confusing for me too, We're great at Bayesian stats and not so great at naming things :facepalm: Thanks for bearing with us

**Pull request closed without merging**
