### PR TITLE
Add example with categorical family

### PR DESCRIPTION
**Pull request by tjburch**
Added a notebook with examples using the categorical family to address #436. I noticed on the original merge (#426) that @tomicapretto made several very nice examples, so I aggregated several into one notebook and added some comments to tie it together. 

Note that I omitted two of the examples, the satisfaction survey and the inhaler example. I made that choice because I think those two fall more in the domain of ordinal regression, rather than categorical. I'm happy to add them if you'd prefer to include them though.

### CODE REVIEW

**Comment by tomicapretto** [comment]
@tjburch thanks a lot for taking the initiative to work on this example notebook. Not many comments from my side as I think it already looks quite clean. On top of that, I think the last example is a good candidate to show how to use the posterior predictive sampling that I'm incorporating on #458.

**Comment by tjburch** [comment]
Sounds good. Once #458 merges, I'll add a call of the posterior predictive sampling. Thanks for the good examples in the original PR.

**Comment by tomicapretto** [comment]
You can start from the following code. I think it would be nice to add a legend like the default in https://arviz-devs.github.io/arviz/api/generated/arviz.plot_ppc.html.

```python
model.predict(idata, kind="pps")

draws = np.prod(idata.posterior_predictive["choice"].shape[:2])
choices = ["Other", "Invertebrates", "Fish"]

pps = idata.posterior_predictive["choice"].values.reshape(draws, 63)

y = np.zeros((draws, len(choices)))
for i in range(draws):
    for j, value in enumerate(choices):
        y[i, j] = np.sum(pps[i] == value)

y = y / y.sum(axis=1)[:, None]

fig, ax = plt.subplots(figsize=(8, 5))
x = np.arange(len(choices))

for i in range(draws):
    ax.hlines(y[i], xmin=x - 0.5, xmax=x + 0.5, alpha=0.05)
ax.hlines(y.mean(0), xmin=x - 0.5, xmax=x + 0.5, color="C0", lw=2, ls="--")

true_counts = data["choice"].value_counts().sort_index()
true_counts = true_counts / true_counts.sum()
ax.hlines(true_counts, xmin=x - 0.5, xmax=x + 0.5, color="black", lw=2)

ax.set_xticks(x)
ax.set_xticklabels(choices)
ax.set_xlabel("Choice")
ax.set_ylabel("Probability");
```

image


@aloctavodia  do you know why `az.plot_ppc` does not work with discrete values? I get an error similar to the one here https://github.com/arviz-devs/arviz/pull/1882

**Comment by aloctavodia** [comment]
> You can start from the following code. I think it would be nice to add a legend like the default in https://arviz-devs.github.io/arviz/api/generated/arviz.plot_ppc.html.
> 
> ```python
> model.predict(idata, kind="pps")
> 
> draws = np.prod(idata.posterior_predictive["choice"].shape[:2])
> choices = ["Other", "Invertebrates", "Fish"]
> 
> pps = idata.posterior_predictive["choice"].values.reshape(draws, 63)
> 
> y = np.zeros((draws, len(choices)))
> for i in range(draws):
>     for j, value in enumerate(choices):
>         y[i, j] = np.sum(pps[i] == value)
> 
> y = y / y.sum(axis=1)[:, None]
> 
> fig, ax = plt.subplots(figsize=(8, 5))
> x = np.arange(len(choices))
> 
> for i in range(draws):
>     ax.hlines(y[i], xmin=x - 0.5, xmax=x + 0.5, alpha=0.05)
> ax.hlines(y.mean(0), xmin=x - 0.5, xmax=x + 0.5, color="C0", lw=2, ls="--")
> 
> true_counts = data["choice"].value_counts().sort_index()
> true_counts = true_counts / true_counts.sum()
> ax.hlines(true_counts, xmin=x - 0.5, xmax=x + 0.5, color="black", lw=2)
> 
> ax.set_xticks(x)
> ax.set_xticklabels(choices)
> ax.set_xlabel("Choice")
> ax.set_ylabel("Probability");
> ```
> 
> image
> 
> @aloctavodia do you know why `az.plot_ppc` does not work with discrete values? I get an error similar to the one here [arviz-devs/arviz#1882](https://github.com/arviz-devs/arviz/pull/1882)

Not sure. I will check. I recently used `az.plot_ppc` with discrete data and it worked

**Comment by tjburch** [comment]
<p>Added to the discussion below, </p><p> </p><blockquote>Of note, the posterior means predicted by Bambi contain information about all&nbsp;n categories (despite having only&nbsp;n−1&nbsp;coefficients), so we can directly construct this plot, rather than manually calculating&nbsp;1−(p1+p2)&nbsp;for the third class.&nbsp;</blockquote><p> </p><p> </p>

---

 <a href='https://app.reviewnb.com/bambinos/bambi/pull/457/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by tjburch** [comment]
<p>Nice - applied.</p>

---

 <a href='https://app.reviewnb.com/bambinos/bambi/pull/457/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by tjburch** [comment]
Sorry about the delay on getting these changes in, ran into some issues and been a busy week. I think it should be up-to-date with everything mentioned. If there's anything else you'd like me to add/edit, let me know!

**Comment by aloctavodia** [comment]
Thanks, I just added two small comments. After addressing those I think this is ready to be merged!

**Comment by tjburch** [comment]
Last couple of comments should be taken care of in the latest commit!

**Comment by tomicapretto** [comment]
Thanks @tjburch for working on another example!

**Comment by tjburch** [comment]
@tomicapretto you did all the hard work, I just put it together and added some fluff :)

Happy to do it.

**Pull request merged**
