### PR TITLE
Fix double uppercase letters in docs

### PR DESCRIPTION
**Pull request by cpfiffer**
Not sure if this is intentional or not -- feel free to close if it was intentional.

### CODE REVIEW

**Comment by ahartikainen** [comment]
BAyesian Model-Building Interface
BA.... M.... B.... I...

**Comment by ColCarroll** [comment]
Its a good point that maybe the name should have been `BAMBI`. What if we wrote **Ba**yesian **m**odel-**b**uilding **i**nterface, so the letter casing at least matches?

**Comment by cpfiffer** [comment]
Sorry for the noise, didn't even see the header at the top of the README! I'll sit in my room, now.

**Comment by aloctavodia** [comment]
@cpfiffer do not worry! I think @ColCarroll have a good point.

**Pull request closed without merging**
