### PR TITLE
Add nicer print method for several objects

### PR DESCRIPTION
**Pull request by tomicapretto**
I think clearer `.__repr__()` methods can be beneficial to newcomers.

So far, I've implemented this for Prior.

Using priors from this example

`model.terms["Time"].prior`
`Normal(mu: 0, sigma: 2.1449214550272586)`

`model.terms["1|Pig"].prior`
```
Normal(
  mu: 0,
  sigma: HalfNormal(sigma: 16.504333838133107)
)
```

### CODE REVIEW

**Comment by tomicapretto** [comment]
```python
model.family
```
```
Gaussian family
----------------
Link:
  identity
Prior:
  Normal(
    mu: Elemwise{add,no_inplace}.0,
    sigma: HalfStudentT(nu: 4, sigma: 24.964371349924743)
  )
```

I think we may change what is printed for `mu`, and any other `family.parent` value, so it is clearer that is the parameter being modeled by the linear predictor and that, in this case, `sigma` is the prior for the error term.

**Comment by tomicapretto** [comment]
This looks better and is less confusing I think.
```python
model.family
```
```
Gaussian family
----------------
Response distribution: Gaussian
Link: identity
Priors:
  sigma: HalfStudentT(nu: 4, sigma: 24.964371349924743)
```

**Comment by tomicapretto** [comment]
This is how it works for `Model` objects. 
```python
model
```
```
Formula: Weight ~ Time + (Time|Pig)
Family name: Gaussian
Link: identity
Priors:
  Intercept ~ Normal(mu: 60.7257686062718, sigma: 28.5863447527248)
  Time ~ Normal(mu: 0, sigma: 2.1449214550272586)
  1|Pig ~ Normal(mu: 0, sigma: HalfNormal(sigma: 16.504333838133107))
  Time|Pig ~ Normal(mu: 0, sigma: HalfNormal(sigma: 2.1449214550272586))
  sigma ~ HalfStudentT(nu: 4, sigma: 24.964371349924743)
------
* To see a plot of the priors call model.plot_priors()
* To see a summary or a plot of the posterior call az.summary(fitted) or az.plot_trace(fitted)
```
Please comment about your opinions on this. whether it is necessary, unnecessary, nice, bad, whatever.

**Comment by tomicapretto** [comment]
If the model is built but not fitted, we'll see something like

```
Formula: Weight ~ Time + (Time|Pig)
Family name: Gaussian
Link: identity
Priors:
  Intercept ~ Normal(mu: 60.725769, sigma: 28.586345)
  Time ~ Normal(mu: 0, sigma: 2.1449215)
  1|Pig ~ Normal(mu: 0, sigma: HalfNormal(sigma: 16.504334))
  Time|Pig ~ Normal(mu: 0, sigma: HalfNormal(sigma: 2.1449215))
  sigma ~ HalfStudentT(nu: 4, sigma: 24.964371)
------
* To see a plot of the priors call the .plot_priors() method.
```

But if the model is fitted, we have a message about using ArviZ

```
Formula: Weight ~ Time + (Time|Pig)
Family name: Gaussian
Link: identity
Priors:
  Intercept ~ Normal(mu: 60.725769, sigma: 28.586345)
  Time ~ Normal(mu: 0, sigma: 2.1449215)
  1|Pig ~ Normal(mu: 0, sigma: HalfNormal(sigma: 16.504334))
  Time|Pig ~ Normal(mu: 0, sigma: HalfNormal(sigma: 2.1449215))
  sigma ~ HalfStudentT(nu: 4, sigma: 24.964371)
------
* To see a plot of the priors call the .plot_priors() method.
* To see a summary or plot of the posterior pass the object returned by .fit() to az.summary() or az.plot_trace()
```

**Comment by twiecki** [comment]
This is awesome! Can it also output latex?

**Comment by tomicapretto** [comment]
I hadn't think about latex, but I definitely think it would be nice to have that as well. Were you thinking about printing only the priors with latex or anything else? 

In the long term, something like R package [equatiomatic](https://cran.r-project.org/web/packages/equatiomatic/vignettes/intro-equatiomatic.html) would be awesome. But maybe that is too ambitious for Bambi right now.

**Comment by twiecki** [comment]
Yes, exactly. PyMC3 already does this, which makes me wonder if that funcionality could be useful here too.

**Pull request merged**
