### PR TITLE
Predict new groups docs

### PR DESCRIPTION
**Pull request by GStechschulte**
This PR adds docs for the new `sample_new_groups` arg. in `model.predict()` that was merged in PR #693. The notebook explains the motivation for the new arg. (related to hierarchical models) and how to use it to predict new groups either: directly with  `model.predict()`, or with `bmb.interpret.comparisons`.

### CODE REVIEW

**Comment by GStechschulte** [comment]
The tests failing are related to issue PyMC issue [#6941](https://github.com/pymc-devs/pymc/issues/6941).

**Comment by tomicapretto** [comment]
@GStechschulte it's already in very good shape, just some minor comments.

**Comment by GStechschulte** [comment]
<p>The patient ID's are long, e.g., <code>ID00007637202177411956430</code> and I wanted it to be patient 1, 2, 3, etc. But yeah, we should avoid the dependence. </p><p> </p><p>Yes, since <code>weeks</code> and <code>fvc</code> aren't on the same scale.</p><p> </p>

---

 <a href='https://app.reviewnb.com/bambinos/bambi/pull/734/discussion/#comment-1754127780'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by GStechschulte** [comment]
<p>Nope, and increasing draws reduces the autocorrelation, and nope :)</p>

---

 <a href='https://app.reviewnb.com/bambinos/bambi/pull/734/discussion/#comment-1754127860'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by GStechschulte** [comment]
<p>Yup, good catch!</p><p> </p>

---

 <a href='https://app.reviewnb.com/bambinos/bambi/pull/734/discussion/#comment-1754127885'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by GStechschulte** [comment]
<p>I am a bit confused on the "deflection" terminology. When you say "deflection" are you describing "variation"? For example, </p><p> </p><blockquote>However, we do include a deflection around the&nbsp;weeks&nbsp;slope with&nbsp;weeks | patient</blockquote><p> </p><p>Is like saying "the weeks slope is allowed to vary by individual patients"?</p><p> </p><p>Edit: I just looked up deflection regarding statistical modelling:</p><p> </p><blockquote> "deflection" is often used to describe how coefficients (typically regression coefficients) deviate or vary from some reference point. It is a way to express how the effect of a predictor variable varies across different groups or levels of that variable.</blockquote><p> </p>

---

 <a href='https://app.reviewnb.com/bambinos/bambi/pull/734/discussion/#comment-1754127810'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by GStechschulte** [comment]
<p>Thank you! :)</p>

---

 <a href='https://app.reviewnb.com/bambinos/bambi/pull/734/discussion/#comment-1754127754'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by GStechschulte** [comment]
> @GStechschulte it's already in very good shape, just some minor comments.

Thanks for the kind words and review! Much appreciated!

**Comment by tomicapretto** [comment]
<p>Makes sense. I get it makes things easier later when you want to predict for particular individuals. Maybe this can be achieved by doing something like </p><p> </p><p><code>series.map({series: np.arange(len(series))}.astype(object)</code>  <span class="ql-cursor">﻿</span></p>

---

 <a href='https://app.reviewnb.com/bambinos/bambi/pull/734/discussion/#comment-1754127780'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by tomicapretto** [comment]
@GStechschulte looks perfect, thanks!

**Pull request merged**
