### PR TITLE
Add multinomial family

### PR DESCRIPTION
**Pull request by tomicapretto**
With Bambi

```python
import arviz as az
import bambi as bmb
import numpy as np
import pandas as pd

az.style.use("arviz-darkgrid")
rng = np.random.default_rng(0)

def c(*args):
    return np.column_stack(args)

n = 15
size = 10
data = pd.DataFrame(
    {
        "y1": rng.binomial(n, 0.3, size),
        "y2": rng.binomial(n, 0.5, size),
        "y3": rng.binomial(n, 0.7, size),
        "x": rng.normal(size=size)
    }
)

bmb_model = bmb.Model("c(y1, y2, y3) ~ x", data, family="multinomial")
idata = bmb_model.fit(random_seed=0)

bmb_model.predict(idata)
az.plot_trace(idata);
```

image

With PyMC3

```python
import arviz as az
import bambi as bmb
import numpy as np
import pandas as pd
import pymc3 as pm
import theano.tensor as tt

from formulae import design_matrices

az.style.use("arviz-darkgrid")

rng = np.random.default_rng(0)

def c(*args):
    return np.column_stack(args)

n = 15
size = 10
data = pd.DataFrame(
    {
        "y1": rng.binomial(n, 0.3, size),
        "y2": rng.binomial(n, 0.5, size),
        "y3": rng.binomial(n, 0.7, size),
        "x": rng.normal(size=size)
    }
)

dm = design_matrices("c(y1, y2, y3) ~ x", data)
Y = dm.response.design_matrix
X = dm.common.design_matrix

coords = {"x_dim": ["b", "c"]}
with pm.Model(coords=coords) as model:
    
    b0 = pm.Normal("b0", dims="x_dim")
    b1 = pm.Normal("b1", dims="x_dim")
    
    # Prepend one dimension bc response multicategorical and predictor 1 dimensional
    b = tt.concatenate([b0[np.newaxis, :], b1[np.newaxis, :]])
    
    nu = pm.math.dot(X, b)
    
    nu = tt.concatenate([np.zeros((Y.shape[0], 1)), nu], axis=1)
    
    # Must add up to 1 in the last axis
    p = pm.Deterministic("p", tt.nnet.softmax(nu))
    
    response = pm.Multinomial("response", n=Y.sum(axis=1)[:, None], p=p, observed=Y)

with model:
    idata = pm.sample(return_inferencedata=True, random_seed=0)

az.plot_trace(idata);
```
image

### CODE REVIEW

**Comment by zwelitunyiswa** [comment]
Nice! I do love multinomial regression -- and will be cool to do in Bambi. Thanks, Tomi!

**Comment by zwelitunyiswa** [comment]
@tomicapretto how do I install this branch to try this? I tried: 

!pip install git+https://github.com/tomicapretto/bambi.git@9f3d77891750c6d12de5936563da796f7b1cebef

But I am getting errors. See attached.

Screen Shot 2022-04-20 at 12 08 11 PM

**Comment by tomicapretto** [comment]
I think you could clone the repo and the branch and install locally from there?

With git in this branch I simply do `pip install .`

**Comment by tomicapretto** [comment]
@zwelitunyiswa you can install from the main branch now

**Comment by zwelitunyiswa** [comment]
> @zwelitunyiswa you can install from the main branch now

Yup, that works! Thank you.

**Comment by zwelitunyiswa** [comment]
@tomicapretto I get an error when I try to fit a partial pooling model. Am I doing something wrong (i.e. this is not possible with multinomial regression) or is it an error in the software? I have attached a screenshot and test data (in feather format, which pandas should read).

Screen Shot 2022-04-22 at 10 16 44 AM

[test_data.feather.zip](https://github.com/bambinos/bambi/files/8541699/test_data.feather.zip)

**Comment by tomicapretto** [comment]
> @tomicapretto I get an error when I try to fit a partial pooling model. Am I doing something wrong (i.e. this is not possible with multinomial regression) or is it an error in the software? I have attached a screenshot and test data (in feather format, which pandas should be able to read).
> 
> Screen Shot 2022-04-22 at 10 16 44 AM
> 
> [test_data.feather.zip](https://github.com/bambinos/bambi/files/8541699/test_data.feather.zip)

Could you open an issue with the data and the reproducible example please? That would be very helpful.

**Comment by zwelitunyiswa** [comment]
> > @tomicapretto I get an error when I try to fit a partial pooling model. Am I doing something wrong (i.e. this is not possible with multinomial regression) or is it an error in the software? I have attached a screenshot and test data (in feather format, which pandas should be able to read).
> > Screen Shot 2022-04-22 at 10 16 44 AM
> > [test_data.feather.zip](https://github.com/bambinos/bambi/files/8541699/test_data.feather.zip)
> 
> Could you open an issue with the data and the reproducible example please? That would be very helpful.

Sorry about that - bad Git manners. I have opened a new issue.

**Pull request merged**
