### PR TITLE
Use number of rows from out-of-sample data in multivariate families

### LINKED ISSUE #845: .predict() data, needs same number of samples as .fit() with kind="response"
I stumbled upon an issue that I believe was not present in earlier versions (~0.10)

I have data in `reference_df` where I fit a model on, using this model I would like to do predictions on additional data stored in `target_df`.

```python
  formula = "c(a, b, c, d) ~ age + BMI"
  model = bmb.Model(
      formula,
      reference_df,
      family="multinomial",
  )
  trace = model.fit(
      random_seed=0, chains=4, draws=1000, cores=4
  )

  model.predict(
                trace,
                data=target_df.sample(reference_df.shape[0], replace=True),
                kind="response",
            )
```

Then I pick the trace's posterior_predictive apart to get the stats I need.

This used to work (back when kind="pps" was still the norm) without the `.sample()` step to get the same number of observations in both groups. 

Is this intentional or did I stumble upon a bug or is this on me? For my use-case I don't think it matters much, though it probably adds a bit more randomness and uncertainty to the results.

### PR DESCRIPTION
**Pull request by tomicapretto**
This PR closes #845

### CODE REVIEW

**Comment by GStechschulte** [comment]
Do you want a review of this? :)

**Comment by tomicapretto** [comment]
> Do you want a review of this? :)

Sure, it can't hurt :)

But I'm also waiting for a response here https://github.com/bambinos/bambi/issues/845#issuecomment-2366965478

**Comment by sepro** [comment]
> > Do you want a review of this? :)
> 
> Sure, it can't hurt :)
> 
> But I'm also waiting for a response here [#845 (comment)](https://github.com/bambinos/bambi/issues/845#issuecomment-2366965478)

Currently trying to have a look, will let you know if this resolves the issue I had ! (Hopefully some time this week)

**Comment by tomicapretto** [comment]
> > > Do you want a review of this? :)
> > 
> > 
> > Sure, it can't hurt :)
> > But I'm also waiting for a response here [#845 (comment)](https://github.com/bambinos/bambi/issues/845#issuecomment-2366965478)
> 
> Currently trying to have a look, will let you know if this resolves the issue I had ! (Hopefully some time this week)

thanks!

**Comment by sepro** [comment]
Have been able to install this branch and run my code and can confirm this now works with a different set of observations when predicting.

**Review by GStechschulte — APPROVED** [review]
Great!! :)

**Pull request merged**
