### PR TITLE
Add posterior predictive example to drugs and some other fixes

### PR DESCRIPTION
**Pull request by canyon289**
Changed broken indexing in pig example
Made some typo fixes

### CODE REVIEW

**Comment by canyon289** [comment]
This is rebased on the github actions branch

**Review by aloctavodia — APPROVED** [review]
LGTM!

**Comment by canyon289** [comment]
Let me rebase on master before merging. Theres too many files in this comment

**Comment by tomicapretto** [comment]
Now we have conflicts here, because of updates I've made to those notebooks. I think we can merge this once we have conflicts resolved and notebooks re-run with main branch.

**Comment by canyon289** [comment]
No problem I'll resolve the conflicts

**Pull request closed without merging**
