### PR TITLE
update travis config

### PR DESCRIPTION
**Pull request by aloctavodia**
Attempt to fix conflict with conda and current travis configuration

### CODE REVIEW

**Comment by aloctavodia** [comment]
OK, Travis is working again, but they seem unrelated to this PR. @tyarkoni do you have any hint?

**Comment by tyarkoni** [comment]
Ugh, so many deprecation warnings... I think the whole codebase is in need of some spring cleaning. :(

Can't tell what's going wrong at a glance. The proximal problem looks to be in the renaming of the Stan  outputs, but hard to say if that's because something's breaking in Stan, PyStan, or Bambi itself (I haven't kept up with Stan developments, so if there have been changes to the language, it wouldn't shock me if the back-end no longer works properly). I'll try to find the time to look at this, but can't promise that it'll be very soon. @jake-westfall, any immediate insights?

**Comment by ahartikainen** [comment]
We changed to 1 based indexing in PyStan 6 months ago

**Comment by tyarkoni** [comment]
Ah, well that almost certainly explains it. :) Will try to work up a fix shortly.

**Comment by aloctavodia** [comment]
I can also help with the spring cleaning. Can we accept PRs even when failing until the spring cleaning is done?

**Comment by tyarkoni** [comment]
In principle, yes. But I should have a fix for this very shortly (it was indeed the 1-off error), so let's wait at least for that. If there are failures beyond that, accepting PRs anyway seems fine.

**Comment by aloctavodia** [comment]
Sounds good to me!

**Comment by tyarkoni** [comment]
The Python 2 tests now pass, so if you merge the changes in #136, we should be good to go. Thanks!

**Pull request merged**
