### PR TITLE
Add model evaluation to logistic regression example

### PR DESCRIPTION
**Pull request by agustinaarroyuelo**
I added a small section for model evaluation using separation plot and khat plot.

### CODE REVIEW

**Comment by tomicapretto** [comment]
> View / edit / reply to [this conversation](https://app.reviewnb.com/bambinos/bambi/pull/350/discussion/) on ReviewNB
> 
> _tomicapretto commented on 2021-05-12T12:13:11Z_
> ----------------------------------------------------------------
> 
> I tried with a white text but it wasn't too clear either. The following seems to be clearer. But feel free not to include it if you feel it adds unnecesary complexity.
> 
> import matplotlib.patheffects as pe
> ax = az.plot_separation(clinton_fitted, y='vote', figsize=(9,0.5));
> 
> y = [0.2, 0.7, 0.2, 0.2]
> 
> 
> for x, y in zip(influential_observations, y):
> 
>     text = str(x) 
> 
>     x = x / len(clinton_data)
> 
>     ax.scatter(x, y, marker='+', s=50, color='orange', zorder=3)    
> 
>     ax.text(x, y, text, color="white", path_effects=[pe.withStroke(linewidth=2, foreground="black")]);

This is the result

image

**Comment by tomicapretto** [comment]
Thank you so much for opening this PR with the model evaluation. This is the first time we have such work in our examples and it's a great contribution :)

**Comment by tomicapretto** [comment]
I'll leave the PR open for a couple of days if somebody wants to add something to this example, but it is almost finished for me. Just review a couple of typos, resolve one issue about the random seed, and that's it :smile:

**Comment by agustinaarroyuelo** [comment]
Thank you @tomicapretto for you comments and help!

**Review by aloctavodia — APPROVED** [review]
Great addition, I have a few nitpicks.

**Pull request merged**
