### PR TITLE
Add automatic versioning

### PR DESCRIPTION
**Pull request by tomicapretto**
With this PR I add `setuptools_scm`. It helps to handle automatic versioning. It takes the version from git tags, and then it adds some stuff to make it unique. This way, we get unique version numbers for different commits and people can install from git with more ease.

### CODE REVIEW

**Comment by tomicapretto** [comment]
I don't know why commits from @jt-lab keep appearing in all my PRs. Do any of you know what I'm missing? @GStechschulte @aloctavodia @canyon289

**Comment by canyon289** [comment]
It looks like the merge you attempted caused the issues. do you want help cleaning up the commit tree?

**Comment by tomicapretto** [comment]
> It looks like the merge you attempted caused the issues. do you want help cleaning up the commit tree?

Is it fixed if I just delete the repo and create it again? I know there are more professional ways but my guess is it's going to be painful haha

**Comment by canyon289** [comment]
I wouldnt delete the repo.......

You could create a new branch on top of main and copy over your changes and then force push to this PR, thats what I'd reccomend

**Pull request merged**
