### PR TITLE
Added bayesian frequentist comparison notebook using statsmodels. Ren…

### PR DESCRIPTION
**Pull request by ejolly**
…amed older pymer4 comparison notebook.

### CODE REVIEW

**Comment by camenpihor** [comment]
Thanks for this! As a way to learn I tried to reproduce the Bayesian Frequentist Tutorial using statsmodel, and it took me a couple days and you did it so fast! haha

**Comment by ejolly** [comment]
Haha sure thing. The only reason I seem fast is because I paid in "blood" aka too much time banging my head against statsmodels before just getting frustrated and creating pymer4.

**Comment by camenpihor** [comment]
hahahaha that's fair :p

**Comment by aloctavodia** [comment]
Hi @ejolly, it seems with the last changes we introduced some conflicts with your PR. Sorry about that. Could you please fix this?

**Comment by ejolly** [comment]
Sure thing. I just pulled in the latest changes and merged without conflicts locally, so I'm hoping my PR is merge-able after the tests pass.

**Pull request merged**
