### PR TITLE
Added missing doc string part for center_predictors

### PR DESCRIPTION
**Pull request by jt-lab**
Added missing doc string part for center_predictors

Perhaps the rationale behind centering could be added to help user decide whether to turn it on or not. But I'm not entirely sure about this.

### CODE REVIEW

**Comment by tomicapretto** [comment]
Thanks a lot for the contribution! The only thing I would add is that this changes the interpretation of the prior on the intercept, as it's on the intercept after the data was centered.

**Comment by jt-lab** [comment]
> Thanks a lot for the contribution! The only thing I would add is that this changes the interpretation of the prior on the intercept, as it's on the intercept after the data was centered.

Added! This was a good point. The zero-centered priors from some examples were  actually how we stumbled on the data being automatically centered in the first place.

**Comment by tomicapretto** [comment]
@jt-lab CI is failing because of `black`. Can you fix it? If you can't, I can do it for you :) 

Reference: https://github.com/bambinos/bambi/actions/runs/6273481237/job/17037212920?pr=726

**Comment by jt-lab** [comment]
> @jt-lab CI is failing because of `black`. Can you fix it? If you can't, I can do it for you :)
> 
> Reference: https://github.com/bambinos/bambi/actions/runs/6273481237/job/17037212920?pr=726

I'll fix it. At least I'll try! I thought I couldn't break anything just changing a docstring... but I was wrong! :-)

**Comment by jt-lab** [comment]
> > @jt-lab CI is failing because of `black`. Can you fix it? If you can't, I can do it for you :)
> > Reference: https://github.com/bambinos/bambi/actions/runs/6273481237/job/17037212920?pr=726
> 
> I'll fix it. At least I'll try! I thought I couldn't break anything just changing a docstring... but I was wrong! :-)

BTW: When running the tests I got these seemingly unrelated errors:
FAILED tests/test_hsgp.py::test_minimal_1d_fits - ValueError: Incompatible Elemwise input shapes [(100,), (10,)]
FAILED tests/test_hsgp.py::test_minimal_1d_predicts - ValueError: Incompatible Elemwise input shapes [(100,), (10,)]

**Comment by tomicapretto** [comment]
@jt-lab I just saw those errors too. I think it's due to some change upstream. I'll merge this because this is an unrelated change. We'll have to figure the problem out in a separate PR (or maybe it's fixed upstream). Thanks for the contribution! :smile:

**Pull request merged**
