### PR TITLE
Update documentation following good inferencedata practices

### LINKED ISSUE #538: Update docs to follow good InferenceData practices
We should update our documentation to follow "good InferenceData" practices. By this I mean to use InferenceData/xarray methods and ArviZ functions like `extract_dataset` to work with InferenceData and, if possible, avoid transforming InferenceData object to other object like arrays of dictionaries. 

* [x] [Getting started](https://bambinos.github.io/bambi/main/notebooks/getting_started.html)
* [x] [Comparison of two means (T-test)](https://bambinos.github.io/bambi/main/notebooks/t-test.html)
* [x] [Multiple linear regression](https://bambinos.github.io/bambi/main/notebooks/ESCS_multiple_regression.html)
* [x] [Regression splines (Cherry blossom example)](https://bambinos.github.io/bambi/main/notebooks/splines_cherry_blossoms.html)
* [x] [Hierarchical Linear Regression (Pigs dataset)](https://bambinos.github.io/bambi/main/notebooks/multi-level_regression.html)
* [x] [Hierarchical Linear Regression (Sleepstudy example)](https://bambinos.github.io/bambi/main/notebooks/sleepstudy.html)
* [x] [Hierarchical Linear Regression (Radon Contamination dataset)](https://bambinos.github.io/bambi/main/notebooks/radon_example.html)
* [x] [Bayesian Workflow (Strack RRR Analysis Replication)](https://bambinos.github.io/bambi/main/notebooks/Strack_RRR_re_analysis.html)
* [x]  [Bayesian Workflow (Police Officer’s Dilemma)](https://bambinos.github.io/bambi/main/notebooks/shooter_crossed_random_ANOVA.html)
* [x] [Robust Linear Regression](https://bambinos.github.io/bambi/main/notebooks/t_regression.html)
* [x]  [Logistic Regression (Vote intention with ANES data)](https://bambinos.github.io/bambi/main/notebooks/logistic_regression.html)
* [x] [Logistic Regression and Model Comparison with Bambi and ArviZ](https://bambinos.github.io/bambi/main/notebooks/model_comparison.html)
* [x] [Hierarchical Logistic regression with Binomial family](https://bambinos.github.io/bambi/main/notebooks/hierarchical_binomial_bambi.html)
* [x] [Regression for Binary responses: Alternative link functions](https://bambinos.github.io/bambi/main/notebooks/alternative_links_binary.html)
* [x]  [Wald and Gamma Regression (Australian insurance claims 2004-2005)](https://bambinos.github.io/bambi/main/notebooks/wald_gamma_glm.html)
* [x] [Negative Binomial Regression (Students absence example)](https://bambinos.github.io/bambi/main/notebooks/negative_binomial.html)
* [x]  [Beta Regression](https://bambinos.github.io/bambi/main/notebooks/beta_regression.html)
* [x] [Categorical Regression](https://bambinos.github.io/bambi/main/notebooks/categorical_regression.html)
* [x]  [Circular Regression](https://bambinos.github.io/bambi/main/notebooks/circular_regression.html)

### PR DESCRIPTION
**Pull request by aloctavodia**
Closes #538

### CODE REVIEW

**Comment by tomicapretto** [comment]
Only small comments. I think this can be merged.

Apart from that, I've seen some examples where the density estimates were terribly wiggly. Now it is fixed. Do you know why that happened?

**Comment by aloctavodia** [comment]
Thanks for the comments, I will address them and also add the rest of the notebooks, I am almost finished making changes.

No idea what happened with the  wigglyness, is a complete mystery to me.

**Comment by aloctavodia** [comment]
We are good to merge, unless there are more comments @tomicapretto

**Comment by tomicapretto** [comment]
Looks good! Let's merge now :)

**Pull request merged**
