### PR TITLE
Improve computation of effective sample size

### PR DESCRIPTION
**Pull request by junpenglao**
Cherrypicking the pymc3 PR: https://github.com/pymc-devs/pymc3/pull/2854. More information see https://github.com/pymc-devs/pymc3/issues/2810

### CODE REVIEW

**Comment by tyarkoni** [comment]
Awesome, thanks!

This is exactly what's in PyMC3, right? @jake-westfall one thing we should consider is reverting to the former state of affairs where PyMC3 was a hard dependency. I doubt many people will have major objections to installing PyMC3 (even those who intend to use the Stan back-end). That way we could just pull this stuff out of PyMC3 rather than having to maintain the same code in two places.

Also, I notice one test seems to be failing, but can't take a careful look right now to see if it's something that was introduced by this PR, or random travis breakage. Will look at it when I can.

**Comment by junpenglao** [comment]
Yep this is exactly what is in PyMC3. 

Actually you can call `pm.effective_n` as well, as it also accept numpy array with the right shape. Alternatively, we can expose the `get_neff` function so you can import it directly.

I think in the long run it might be useful to break out the diagnostic and visualization code to have a library similar to `coda` in R. 

The travis fail doesnt seem to related to this PR (actually I dont think you have a test for diagnostic), but seems it is a legit test fail.

**Comment by tyarkoni** [comment]
Sorry about the absurdly long delay--forgot to follow up on the testing issue at the time. Thanks!

**Comment by junpenglao** [comment]
No worries! We are developing https://github.com/arviz-devs/arviz which are cross backend (pymc3 and pystan currently), will likely implement faster version of effective sample size inside soon.

**Pull request merged**
