### PR TITLE
Since we moved to python3, we can remove string_types from six for str

### PR DESCRIPTION
**Pull request by camenpihor**

### CODE REVIEW

**Comment by ColCarroll** [comment]
Looks good to merge (-900 lines!), but needs a rebase.

**Comment by camenpihor** [comment]
Phew, rebased!

**Comment by camenpihor** [comment]
Thanks @tyarkoni @ColCarroll and @aloctavodia  :) 

And thanks for allowing me to help out, I've been having a lot of fun learning about the library and more python!

**Comment by aloctavodia** [comment]
Thanks for your contributions!

**Pull request merged**
