### PR TITLE
[WIP] Fix HSGP predictions

### LINKED ISSUE #776: `plot_predictions` breaks with HSGP
The attached dataset will help reproduce the issue, but basically:
```python
formula = "p(Campus_Living, N) ~ 1 + (1 | Age_Group) + (1 | Major) + hsgp(Fall_Year, by=Age_Group, m=10, c=2, scale=True, centered=True) + hsgp(Fall_Year, by=Major, m=10, c=2, scale=True, centered=True)"

m_bambi = bmb.Model(
    formula=formula,
    data=data,
    family="binomial",
    categorical=["Age_Group", "Major"],
)
m_bambi.build()
idata_bambi = m_bambi.fit()

## this line fails
bmb.interpret.plot_predictions(
    m_bambi, 
    idata_bambi,
    conditional={"Fall_Year": np.linspace(2012, 2025)},
);
```
yields (full traceback at end of post):
```python
IndexError: index -1 is out of bounds for axis 1 with size 0
```

If you do `formula = "p(Campus_Living, N) ~ 1 + hsgp(Fall_Year, by=Age_Group, m=10, c=2, scale=True, centered=True)"`, the error becomes`KeyError: 'Age_Group'`.

Interestingly, if you change `formula` to `"p(Campus_Living, N) ~ 1 + (1 | Age_Group) + (1 | Major) + hsgp(Fall_Year, by=Age_Group, m=10, c=2, scale=True, centered=True)"` or `"p(Campus_Living, N) ~ 1 + (1 | Age_Group) + hsgp(Fall_Year, by=Age_Group, m=10, c=2, scale=True, centered=True)"`, the plot will display (although I'm not sure it's right)!

It looks like some indexing is happening in `by_values` in `bambi/model_components.py:262`, which yields the error.

Thanks a lot for your help, and LMK if anything is unclear 🙏 

[data.csv](https://github.com/bambinos/bambi/files/14172195/data.csv)

Full error:
```python
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
Cell In[225], line 1
----> 1 bmb.interpret.plot_predictions(
      2     m_bambi, 
      3     idata_bambi,
      4     conditional={"Fall_Year": np.linspace(2012, 2025)},
      5 );

File ~/mambaforge/envs/bayes-workshop/lib/python3.11/site-packages/bambi/interpret/plotting.py:181, in plot_predictions(model, idata, conditional, average_by, target, sample_new_groups, pps, use_hdi, prob, transforms, legend, ax, fig_kwargs, subplot_kwargs)
    174 if average_by is True:
    175     raise ValueError(
    176         "Plotting when 'average_by = True' is not possible as 'True' marginalizes "
    177         "over all covariates resulting in a single prediction estimate. "
    178         "Please pass a covariate(s) to 'average_by'."
    179     )
--> 181 cap_data = predictions(
    182     model=model,
    183     idata=idata,
    184     conditional=conditional,
    185     average_by=average_by,
    186     target=target,
    187     pps=pps,
    188     use_hdi=use_hdi,
    189     prob=prob,
    190     transforms=transforms,
    191     sample_new_groups=sample_new_groups,
    192 )
    194 conditional_info = ConditionalInfo(model, conditional)
    195 transforms = transforms if transforms is not None else {}

File ~/mambaforge/envs/bayes-workshop/lib/python3.11/site-packages/bambi/interpret/effects.py:532, in predictions(model, idata, conditional, average_by, target, pps, use_hdi, prob, transforms, sample_new_groups)
    530     y_hat_mean = y_hat.mean(("chain", "draw"))
    531 else:
--> 532     idata = model.predict(
    533         idata, data=cap_data, sample_new_groups=sample_new_groups, inplace=False
    534     )
    535     y_hat = response_transform(idata["posterior"][response.name_target])
    536     y_hat_mean = y_hat.mean(("chain", "draw"))

File ~/mambaforge/envs/bayes-workshop/lib/python3.11/site-packages/bambi/models.py:832, in Model.predict(self, idata, kind, data, inplace, include_group_specific, sample_new_groups)
    829     else:
    830         var_name = f"{response_aliased_name}_{name}"
--> 832 means_dict[var_name] = component.predict(
    833     idata, data, include_group_specific, hsgp_dict, sample_new_groups
    834 )
    836 # Drop var/dim if already present. Needed for out-of-sample predictions.
    837 if var_name in idata.posterior.data_vars:

File ~/mambaforge/envs/bayes-workshop/lib/python3.11/site-packages/bambi/model_components.py:185, in DistributionalComponent.predict(self, idata, data, include_group_specific, hsgp_dict, sample_new_groups)
    182     linear_predictor_dims = linear_predictor_dims + (response_levels_dim,)
    184 if self.design.common:
--> 185     linear_predictor += self.predict_common(
    186         posterior, data, in_sample, to_stack_dims, design_matrix_dims, hsgp_dict
    187     )
    189 if self.design.group and include_group_specific:
    190     linear_predictor += self.predict_group_specific(
    191         posterior, data, in_sample, to_stack_dims, design_matrix_dims, sample_new_groups
    192     )

File ~/mambaforge/envs/bayes-workshop/lib/python3.11/site-packages/bambi/model_components.py:262, in DistributionalComponent.predict_common(self, posterior, data, in_sample, to_stack_dims, design_matrix_dims, hsgp_dict)
    256 # NOTE:
    257 # The approach here differs from the one in the PyMC implementation.
    258 # Here we have a single dot product with many zeros, while there we have many
    259 # smaller dot products.
    260 # It is subject to change here, but I don't want to mess up dims and coords.
    261 if term.by_levels is not None:
--> 262     by_values = x_slice[:, -1].astype(int)
    263     x_slice = x_slice[:, :-1]
    264     x_slice_centered = (x_slice.data - term.mean[by_values]) / maximum_distance

IndexError: index -1 is out of bounds for axis 1 with size 0
```

### PR DESCRIPTION
**Pull request by tomicapretto**
Fixes predictions when HSGP contains a `by` variable.

* It makes sure the underlying design matrix is not modified until the data of all HSGP components are used.
* Modifies `get_model_covariates` so it also looks at the named arguments of function calls.
  * For this, this PR in formulae was also needed https://github.com/bambinos/formulae/pull/107

~~TODO: implement tests?~~

Edit : it closes #776

### CODE REVIEW

**Comment by GStechschulte** [comment]
Thanks a lot @tomicapretto 👍🏼

**Comment by tomicapretto** [comment]
@GStechschulte could you try this?

```python
import bambi as bmb
import numpy as np
import pandas as pd

df = pd.read_csv("tests/data/gam_data.csv")

rng = np.random.default_rng(1234)
df["fac2"] = rng.choice(["a", "b", "c"], size=df.shape[0])

formula = "y ~ 1 + x0 + hsgp(x1, by=fac, m=10, c=2) + hsgp(x1, by=fac2, m=10, c=2)"
model = bmb.Model(formula, df, categorical=["fac"])
idata = model.fit(tune=500, draws=500, target_accept=0.9)
```

Plot 1

```python
bmb.interpret.plot_predictions(
    model, 
    idata, 
    conditional="x1", 
    subplot_kwargs={"main": "x1", "group": "fac2", "panel": "fac2"},
);
```
image


Plot 2

```python
bmb.interpret.plot_predictions(
    model, 
    idata, 
    conditional={
        "x1": np.linspace(0, 1, num=100),
        "fac2": ["a", "b", "c"]
    }, 
    legend=False,
    subplot_kwargs={"main": "x1", "group": "fac2", "panel": "fac2"},
);
```

image


I was expecting to get the second plot with the code for the first plot. I think we got the result we got because we first generate the data, and only then, we use the `subplot_kwargs`? At that point, it's just too late, you only have one value of `fac2`

**Comment by tomicapretto** [comment]
Thanks @GStechschulte! I think this is done. 

I know the test is actually testing many things at the same time, not just the fix. But I think it's not possible to write a test for the fix in particular, and if possible, it would be so complicated.

**Review by GStechschulte — APPROVED** [review]
LGTM! However, my knowledge on the implementation of HSGP in Bambi is a bit lacking.

**Comment by GStechschulte** [comment]
> Thanks @GStechschulte! I think this is done.
> 
> I know the test is actually testing many things at the same time, not just the fix. But I think it's not possible to write a test for the fix in particular, and if possible, it would be so complicated.

Yup, I agree. It is also nice to have the text for `interpret` in there.

**Pull request merged**
