### PR TITLE
Fix notebooks

### PR DESCRIPTION
**Pull request by camenpihor**
## Changes

- Basically we just need to use `"sigma"` instead of `"sd"` everywhere
- Re-ran notebooks and made sure that they look comparable to the previous versions

## Need to do

- install `pymer4` and run `Bayesian_Frequentist_Tutorial_pymer4.ipynb`
- continue conversation about `shooter_crossed_random_ANOVA.ipynb`

### CODE REVIEW

**Comment by aloctavodia** [comment]
What about focusing on Bayesian examples and remove frequentists ones?

**Comment by camenpihor** [comment]
I'm up for that! Do you want me to remove the frequentist examples in this PR?

**Comment by aloctavodia** [comment]
We can remove the frequentist portion of the example and leave the Bayesian part, right?

**Comment by camenpihor** [comment]
Will do!

**Comment by camenpihor** [comment]
@aloctavodia what do you think about these changes?

**Comment by camenpihor** [comment]
<p>Trying to get this work now. Doesn't work right out of the box, but I can probably fiddle with it</p>

---

 <a href='https://app.reviewnb.com/bambinos/bambi/pull/222/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by camenpihor** [comment]
@aloctavodia Hai! I think this is ready for merging, what do you think?

**Pull request merged**
