### PR TITLE
Attempting to add a CITATION.cff file

### PR DESCRIPTION
**Pull request by tomicapretto**
I've tested the following advice [here](https://github.com/citation-file-format/citation-file-format#validation-heavy_check_mark) and it works, but I'm not sure if the output is going to be good.

### CODE REVIEW

**Comment by tomicapretto** [comment]
Hmm, the generated bibtex looks like

```
@article{Tomas_Bambi_A_simple,
author = {Tomas, Capretto and Camen, Piho and Ravin, Kumar and Jacob, Westfall and Tal, Yarkoni and Osvaldo, Martin},
title = {{Bambi: A simple interface for fitting Bayesian linear models in Python}}
}
```

I'll keep trying

**Comment by tomicapretto** [comment]
I think this is not going to work out of the box right now. The following are going to be useful

* https://github.com/citation-file-format/citation-file-format/issues/254
* https://github.com/precice/fenics-adapter/pull/137 some people with a similar use case

**Comment by aloctavodia** [comment]
It can become annoying if we need to keep updating the release version and date. Maybe we can make that automatic. Or maybe we don't need to worry about this if the preferred citation omits that information.

**Comment by tomicapretto** [comment]
> 

I would keep the citation file in sync with the version used to write the paper. So I don't think we need to update it and what we already have is good.

**Pull request merged**
