### PR TITLE
Reorder requirements; Add matplotlib to requirements.txt

### PR DESCRIPTION
**Pull request by camenpihor**
Tests require matplotlib

I was not sure if python2.7 is still supported, and so I floored the requirement at `2.2.4` so that it would work with python3 as well.

### CODE REVIEW

**Comment by tyarkoni** [comment]
Thanks for the contribution, @camenpihor. I'm not sure we should include MPL in requirements if it's not strictly necessary for most functionality. It's a pretty heavy dependency to foist on people. The test environment can be (and currently is) set up independently. If we want to list matplotlib in `setup.py` as a test requirement, that seems fine as an alternative.

**Comment by ahartikainen** [comment]
`test-requirements.txt` ?

**Comment by ColCarroll** [comment]
+1 requirements-dev.txt. We also did this in pymc3 after [some discussion](https://github.com/pymc-devs/pymc3/issues/793).

**Comment by camenpihor** [comment]
I added a requirements-dev.txt! 

Are there other things that you would like my help with? I took a look at the issues, and would be willing to learn to start tackling them, but would probably need some direction? Or I could start by just familiarizing myself with the library and do some tech-debt-like stuff (use a pylintrc, black, pydocstyle, take a look at speeding up tests, etc.)

Anyways, down to help in any ways that y'all would like :)

**Comment by aloctavodia** [comment]
LGTM.

**Comment by camenpihor** [comment]
Thanks for the comments everyone :)

**Pull request merged**
