### PR TITLE
Add Formula class

### LINKED ISSUE #423: Add Bambi formula object
The brms package has a [`brmsformula()`](https://rdrr.io/cran/brms/man/brmsformula.html) function that is very useful to specify several formulas for different components of the model. If we plan to extend Bambi capabilities and include, for example, Zero Inflated Poisson models, this is going to be something we need to think about.

### PR DESCRIPTION
**Pull request by tomicapretto**
This PR adds a new class called `Formula`. It closes #423. I have added tests. This class is not used within the `Model` class yet. That's going to come in a different PR.

### CODE REVIEW

**Comment by zwelitunyiswa** [comment]
> This PR adds a new class called `Formula`. It closes #423. I have added tests. This class is not used within the `Model` class yet. That's going to come in a different PR.
> 
> 

Very cool! I have played with this in brms and it's incredibly powerful. Can I try it out on the dev branch of Bambi?

**Comment by canyon289** [comment]
❤️

**Comment by tomicapretto** [comment]
> > This PR adds a new class called `Formula`. It closes #423. I have added tests. This class is not used within the `Model` class yet. That's going to come in a different PR.
> 
> Very cool! I have played with this in brms and it's incredibly powerful. Can I try it out on the dev branch of Bambi?

This is not going to have any effect in the meantime. I'm working in another branch to incorporate distributional models in Bambi. Stay tuned :)

**Comment by zwelitunyiswa** [comment]
Cool. Cheers, mate.

**Pull request merged**
