### PR TITLE
Reorder imports; Only import necessary submodules from statsmodels

### LINKED ISSUE #130: statsmodels imports, replace sm
(I'm just following up a link and briefly browsed the source)

`bambi/priors.py` imports `statsmodels.api`
This is not recommended for library use because it imports all of statsmodels and large parts of scipy.
Most of the time it is more efficient and faster in loading to just import the relevant submodules or objects, e.g. just `GLM` class and `families` module

e.g.
```
from statsmodels.genmod.generalized_linear_model import GLM
from statsmodels.genmod import families
```
https://gist.github.com/josef-pkt/61039ab6dc7fb8b502caf5f2050111c0

### PR DESCRIPTION
**Pull request by camenpihor**
Fixes #130 

* Tests successful in python3.6 and python2.7
* I don't know what import order you like, but I am happy to change it to whatever! I was particularly interested in where to place `from bambi.external.six import string_types`

### CODE REVIEW

**Comment by aloctavodia** [comment]
Are all this PR related? If so you should push changes to the same branch (do not create a new one), so commits are added automatically to the same PR, otherwise reviewing changes get more difficult.

**Comment by camenpihor** [comment]
I wrote this PR as standalone since it specifically responds to the issue raised, and the other PRs were responding to other things that I noticed while testing and interacting with the code base. 

I'm completely happy to merge them together, if you want! I just didn't want to bundle perhaps unwanted changes into a PR addressing something that I knew was wanted

**Comment by aloctavodia** [comment]
That's ok. Let's keep separate PRs. Btw, thanks for your contributions

**Comment by aloctavodia** [comment]
I would place from `bambi.external.six import string_types` last

**Comment by tyarkoni** [comment]
I think if we're going ahead with #138, we may as well just remove that import entirely and switch to checking against `str`.

**Comment by aloctavodia** [comment]
Thanks @camenpihor!

**Pull request merged**
