### PR TITLE
Use PyMC v4 

### PR DESCRIPTION
**Pull request by aloctavodia**

### CODE REVIEW

**Comment by tomicapretto** [comment]
Great to see all green here! Sorry I've not been able to check before. Is there anything I could check or do to help?

**Comment by aloctavodia** [comment]
Don't worry!  I think this is ready to merge, nevertheless there is some weird "extra wigllines" in some of the trace plots (the KDEs), even when summaries and other plots looks fine.

**Comment by aloctavodia** [comment]
We no longer need that branch. This PR includes the changes in that branch.

**Comment by canyon289** [comment]
🎉 I vote merging this one

**Comment by aloctavodia** [comment]
I can confirm that the "extra wiglinness" is not due to a chance introduce now and it was already there. So it is most likely related to kde in arviz than bambi.

**Comment by tomicapretto** [comment]
Sorry for being too conservative, but I would vote to merge in main there's an official PyMC release (non-beta). We could also leverage their announcement message (which I think there will be a good one) to say that Bambi also supports v4 now.

I imagine people working with both Bambi and PyMC (which is PyMC3 at the moment). If we make our main branch dependent on PyMC (v4) it may break their installation and it can result in unexpected problems

**Comment by aloctavodia** [comment]
If users work from main they should expect breaks. Only a release should be stable. We will make the next Bambi release once we have PyMC 4.0, but in the meantime we can merge this and even merge other PR, if any that should increase the chance of a stable bambi release.

**Comment by tomicapretto** [comment]
Ok, let's merge then.

**Comment by twiecki** [comment]
You should be able to pin pymc 4.0.0 now and cut a release.

**Pull request merged**
